version: "3.5"
services:
  fhi_navigation:
    image: fraunhoferitalia/fhi_navigation:release
    container_name: fhi_navigation
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
      - CYCLONEDDS_URI=${CYCLONEDDS_URI}
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ../:/fhi_navigation_ws
