version: "3.5"
services:
  fhi_navigation:
    extends:
      file: docker-compose.yml
      service: fhi_navigation
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    privileged: true
